default_collision_operations:
  - object1: platform
    object2: arm
    operation: enable
  - object1: base_link
    object2: arm_link_0
    operation: disable    
  - object1: platform
    object2: gripper
    operation: enable
  - object1: arm
    object2: gripper
    operation: enable
  - object1: gripper_palm_link
    object2: arm_link_5
    operation: disable