TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_rotational_vel: 0.35
  min_in_place_rotational_vel: 0.1
  
  acc_lim_th: 1.0
  acc_lim_x: 0.7
  acc_lim_y: 0.7
  
  holonomic_robot: true
