gripper_controller:
  joint_trajectory_action:
    unit: m
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
    constraints:
      goal_time: 0.6
      gripper_finger_joint_l:
        goal: 0.2
      gripper_finger_joint_r:
        goal: 0.2